create database customer_behaviour
use customer_behaviour
exec sp_rename 'customer_shopping_behavior','customer'

-------BUSINESS PROBLEM

--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue from customer
group by gender


----Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(avg(review_rating),2) as avg_rew_date from customer
group by item_purchased
order by avg_rew_date desc


----Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select avg(purchase_amount) money_spend,shipping_type from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select count(customer_id) ttl_cust,round(avg(purchase_amount),2) avg_spend, 
round(sum(purchase_amount),2) total_revenue, subscription_status from customer
group by subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased, count(*) no_of_item, sum(case when discount_applied = 'Yes' then 1 else 0 end) discount_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*),2) as discount_perct
from customer
group by item_purchased
order by discount_perct desc


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment. 
with customer_type as(
select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_seg
from customer)
select customer_seg, count(*) "total count" from customer_type
group by customer_seg
order by [total count] desc


--Q8. What are the top 3 most purchased products within each category? 
with most as 
(select item_purchased,category,COUNT(*) as cnt,
ROW_NUMBER()over(partition by category order by count(*) desc) as ranks
from customer
group by item_purchased,category)
select category, item_purchased,cnt,ranks from most
where ranks<=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) cnt,subscription_status from customer
where previous_purchases>5 
group by subscription_status


--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) revenue from customer
group by age_group
order by revenue desc